# https://docs.docker.com/compose/networking/
version: '3'
services:
  db:
    image: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=perservant
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d
#  app:
#    image: bartholomews/keyaki
#    ports:
#      - 8080:8080
#    environment:
#      - DATABASE_URL=postgresql://postgres:postgres@db:5432/keyaki
#    depends_on:
#      - db
volumes:
  pgdata: