# https://docs.docker.com/compose/networking/
version: '3'
services:
  db:
    container_name: postgres
    image: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=keyaki
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d
#  app:
#    image: bartholomews/keyaki
#    ports:
#      - 8081:8081
#    environment:
#      - DATABASE_URL=postgresql://postgres:postgres@db:5432/keyaki
#    depends_on:
#      - postgres
volumes:
  pgdata: