version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=postgres
    #    - POSTGRES_PASSWORD=todo
    - POSTGRES_DB=keyaki
    volumes:
    - pgdata:/var/lib/postgresql/data
    - ./docker/postgres:/docker-entrypoint-initdb.d
volumes:
  pgdata: