# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: keyaki
version: '0.0.1-SNAPSHOT'
github: "bartholomews/keyaki"
license: MIT
author: "Federico Bartolomei"
maintainer: "bartholomews"
# synopsis: Japanese SRS [EARLY STAGE WIP].
# description: keyaki is a Japanese SRS project.
# category: SRS

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
#- ../stack.yaml

default-extensions:
- OverloadedStrings
- QuasiQuotes
- GeneralizedNewtypeDeriving
- ConstraintKinds
- FlexibleContexts
- TemplateHaskell
- FlexibleInstances
- NoImplicitPrelude
- ScopedTypeVariables

ghc-options: -Wall

# haskell-scotty
dependencies:
- classy-prelude
- base

library:
  dependencies:
  - scotty
  - postgresql-simple
  - postgresql-simple-migration
  - data-has
  - aeson
  - time
  - mtl
  - regex-compat
  - http-types
  - resource-pool
  - warp-tls
  - warp
  - digestive-functors
  - digestive-functors-aeson
  - lens
  - wai
  - jose-jwt
  - cryptonite
  - slug
  - convertible
  - wai-cors
  - template-haskell
  - wreq
  - http-client
  ghc-options:
  - -Wall
  - -Werror
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  source-dirs: library

executables:
  keyaki:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - directory
    - keyaki
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

benchmarks:
  keyaki-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - keyaki
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  keyaki-test-suite:
    main: Main.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bytestring
    - keyaki
    - hspec
    - postgresql-simple
    - string-random